### ISSUE TITLE
Topic Modelling MemoryError

### ISSUE THREAD

**Issue by Jordantan1999** [jisong316/durg-recommendation#1]
I had issue running at the 22nd cell, how do I solve it?

![image](https://user-images.githubusercontent.com/40348451/125426939-7d413399-ac9e-4cf9-a1d9-6978759fc93e.png)

**Comment by jisong316** [comment]
I think that MemoryError means you ran out of memory, not the code. The code runs ok in my computer, it takes some time tough. Hope this helps.
